### PR TITLE
Mgb scales

### PR DESCRIPTION
**Pull request by DreamNik**
Added support for MGB scales.

### CODE REVIEW

**Comment by KudryavtsevAlex** [comment]
wow, this is what I have searched for about a week. 
Thanks, man, for your job.
You kept me a lot of time: saved me from reverse engineering bluetooth logs...
But it could be a great education studies))
As I understand, MGB will appear in openScale app after accepting your PR by author, mm?

**Comment by KudryavtsevAlex** [comment]
here it is.

8 нояб. 2017 г. 6:55 PM пользователь "OliE" <notifications@github.com>
написал:

**Comment by oliexdev** [comment]
@KudryavtsevAlex thanks but there is no photo attached!?

**Comment by KudryavtsevAlex** [comment]
and now is screenshot attached?
I don't understand, why...

8 нояб. 2017 г. 8:33 PM пользователь "OliE" <notifications@github.com>
написал:

**Comment by oliexdev** [comment]
still not attached you can also send the photo to olie.xdev@googlemail.com via email.

**Comment by DreamNik** [comment]
I've sent photo to olie.xdev@googlemail.com just now.

**Pull request merged**
