### PR TITLE
Make it possible to change order of measurment views

### PR DESCRIPTION
**Pull request by erijo**
By long pressing a view in the data entry activity, the view can be dragged up or down to change the order. The order is then saved and reflected in overview, graph, table and data entry fragments/activity.

This fixes part of #81 (and #164).

### CODE REVIEW

**Comment by oliexdev** [comment]
Great. Just one question is it possible to easily migrate this approach into the preference menu? Because I think it makes more sense to set the order into the preference menu not on the activity.
Like to have a new subpage in Preference->Measurements->Measurement order->Subpage where  you can order the measurements.

**Comment by erijo** [comment]
Yes, I think that is doable. Will look into it.

**Comment by erijo** [comment]
How does this look and feel @oliexdev?

**Comment by oliexdev** [comment]
yeah its awesome big thx @erijo

**Comment by erijo** [comment]
I somehow managed to miss a crash that I introduced. Should be fixed in #200.

**Comment by oliexdev** [comment]
@erijo I noticed in the dark theme the subscreen measurement order preference texts doesn't have the correct white colour. I already tried to change that but I couldn't find the problem yet. Maybe you have an idea?

**Comment by erijo** [comment]
Maybe MeasurementOrderPreference needs to call super with some suitable value for defStyle*?

**Comment by oliexdev** [comment]
fixed with commit https://github.com/oliexdev/openScale/commit/d4a968d6e4991525e7b1ebdf7cc4f2532b841b79

**Pull request merged**
