### PR TITLE
Introduce enum for weight unit and gender

### PR DESCRIPTION
**Pull request by erijo**
Plus a statistics bug fix and a fix for a sometimes (rare) incorrectly calculated age.

### CODE REVIEW

**Comment by oliexdev** [comment]
@erijo can you resolve the conflict please? Thanks in advance.

**Comment by erijo** [comment]
@oliexdev: I have rebased the changes on the latest master now.

**Comment by oliexdev** [comment]
thanks, the source code getting better and better. :smile:

**Comment by oliexdev** [comment]
@erijo somehow the Travis build is failing because the license is not accepted. Before it works with the license bug fix workaround. Do you have an idea how to solve it?
It is also a bit strange that Travis downloaded build-tool version 26.0.2 and not 27.0.2....

**Comment by erijo** [comment]
That's strange. The same commit built fine both on my travis instance and in the pull request. The build-tools version 26.0.2 was installed successfully then.

The simplest way to fix it is probably to add the same workaround for build-tools;26.0.2 as for platforms;android-27.

Btw, have you seen this: https://f-droid.org/en/docs/FAQ_-_App_Developers/#how-do-i-change-the-description-and-add-meta-information-like-screenshots

I noticed that you added some screenshot thing, and if I understand things correctly, fastlane can generate screenshots as well and upload all data to the play store and f-droid.

**Comment by oliexdev** [comment]
Yeah I have seen fastlane but with the build in screenshot function it is also works good, beside I I had to remove the UUID suffixes.

**Pull request merged**
