### PR TITLE
Table view performance improvements

### PR DESCRIPTION
**Pull request by erijo**
The bulk of the changes here (i.e. the last two commits) speeds up loading of the table view by not creating child views that are never displayed and using spanned strings directly instead of via Html.fromHtml. Now it loads almost instant.

Also two clean up commits and a small visual improvement.

### CODE REVIEW

**Comment by erijo** [comment]
With this one could increase number of measurements / page in table view to e.g. 200.

**Comment by erijo** [comment]
After going to bed I realized that 8af0aea9a was probably not the right way to do it, so please hold on merging this, or merge everything except that last commit.

**Comment by erijo** [comment]
There, I redid that last commit to something a little less intrusive. Also increased the number of entries per page in the table view to 50.

**Comment by oliexdev** [comment]
great speed up. I guess using spannable strings instead of using html formatter is much faster.

**Comment by erijo** [comment]
Yes, fromHtml was a big part in the profiling result. But so was all float to string that was done but wasn't used.

**Pull request merged**
