### PR TITLE
Update calculations for OneByone scales

### PR DESCRIPTION
**Pull request by ASerbinski**
Previously, the value reported for muscle mass was lean body mass
less skeletal mass. This was not a correct report for muscle mass
since it included additional values, such as organs and skin mass.

In addition, the impedance value previously used was incorrect.
There were, in fact, two different calculations being performed
for impedance based on data fields that were not relevant to it,
therefore the value for impedance was entirely incorrect, jumpy,
and unpredictable. In fact, the correct bytes for impedance are
the second and third bytes in the data packet received from the
scale, which produces correct and reasonable impedance values.

This commit corrects the prior errors, provides a calculation for
lean body mass, and calculates muscle mass based on the Janssen
formula;

https://journals.physiology.org/doi/pdf/10.1152/jappl.2000.89.2.465

### CODE REVIEW

**Comment by oliexdev** [comment]
Thanks for your PR. did you compare the results with the vendors app for the muscle mass? Do they have the same results?

**Comment by ASerbinski** [comment]
They are absolutely NOT the same results. The vendor software is suggesting muscle mass of around 75-80%, which is simply wrong.

**Comment by oliexdev** [comment]
I don't own this scale but regarding to #159 they provide the muscle mass in kg, maybe the 75-80 are kg?

**Comment by ASerbinski** [comment]
That would bring the muscle mass percentage to 100%.

**Pull request merged**
