### PR TITLE
WIP: Add support for Beurer BF105

### PR DESCRIPTION
**Pull request by jensMF**
I create this to show what I have already done and what is still missing.

### CODE REVIEW

**Comment by jensMF** [comment]
- [ ] register new user with a random consent code
- [ ] connect to a scale user with its consent code
- [ ] use an existing scale user and try to import its information to openScale
- [ ] read the scale user list and save the users to an array
- [ ] read out the bones weight (estimated calculation)
- [ ] read out the bones weight (correct calculation)
- [ ] UI to choose to create a new user
- [ ] UI to enter consent code
- [ ] UI to chose an existing user from the user-list and enter its consent code
- [ ] (optional) read out the upper and lower body values
- [ ] (optional) UI to show the upper and lower body values

**Comment by krisjans** [comment]
Hi @jensMF !
I found your pull-request only after I made similar changes for Beurer BF600 scale: https://github.com/oliexdev/openScale/pull/753
Do you have any plans to continue this project?

**Comment by jensMF** [comment]
Yes, I have plans to continue this projekt. At the moment, I have no spare time for it. I hope this will change in august and/or september.

**Comment by jensMF** [comment]
I would be interested in some bluetooth hci snoop protocols of your scale, to compare it with mine.

**Comment by krisjans** [comment]
@jensMF please check issue https://github.com/oliexdev/openScale/issues/219, there you can find https://github.com/oliexdev/openScale/files/6796523/btsnoop_hci.log from my scale and several other logs from other users.

**Comment by krisjans** [comment]
@jensMF I'm looking at some constants that you added: https://github.com/jensMF/openScale/blob/add_BeurerBF105_support/android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothGattUuidBF105.java#L25-L42 and wondering how you figured those out?

**Comment by jensMF** [comment]
I used the android app "nRF Connect for Mobile".

**Comment by krisjans** [comment]
@jensMF I cherry picked your commit that implements BF105 and based on it I made support for BF600. I also redesigned base-class to allow better code re-use for BF105 and BF600.
I would be appreciate if you could take a look on https://github.com/oliexdev/openScale/pull/753 and probably build and test it on BF105? Any comments welcome! :)

**Comment by oliexdev** [comment]
Does the PR #753 replaced this PR? Can we close this PR?

**Comment by krisjans** [comment]
> Does the PR #753 replaced this PR? Can we close this PR?

PR #753 contains this PR as cherry-picked commit https://github.com/oliexdev/openScale/pull/753/commits/8288b18f4f2681d793a76140baafece557fefe28 . It is not the same as https://github.com/oliexdev/openScale/pull/735/commits/461fad6cce84fe6af6ed66af51c7443d100a1347 because I reduced changes to bare minimum (for example I dropped a bunch of white-space and code formatting changes).

**Comment by jensMF** [comment]
I close this pr in favor of #753

**Pull request closed without merging**
