### PR TITLE
Support for ES-26BB-B

### LINKED ISSUE #900: Scale Support for RENPHO ES-26BB-B
**Scale name**
Scale is RENPHO ES-26BB-B.
Vendor app is [Renpho Health](https://play.google.com/store/apps/details?id=com.renpho.health).

**Bluetooth HCI Snoop log file**

User settings in the vendors app:
```
Sex: Male
Height: 177
Age: 20 (birthday as Jan 1, 2002)
Activity Level: Athlete Mode disabled
sex (male/female), body height, age, activity level
```

I did various measurements with/without socks on, as well as holding some other stuff.

|         Date         | Weight  | BMI  | Body Fat | Fat-free Body Weight | Subcutaneous Fat | Visceral Fat | Body Water | Skeletal Muscle | Muscle Mass | Bone Mass | Protein | BMR  | Metabolic Age |
| :------------------: | ------- | ---- | -------- | -------------------- | ---------------- | ------------ | ---------- | --------------- | ----------- | --------- | ------- | ---- | ------------- |
| Nov 8, 2022 00:44:44 | 60.50kg | 19.3 | -        | -                    | -                | -            | -          | -               | -           | -         | -       | -    | -             |
| Nov 8, 2022 00:45:05 | 60.50kg | 19.3 | 8.5%     | 55.36kg              | 7.6%             | 3            | 66.1%      | 59.1%           | 52.57kg     | 2.79kg    | 20.9%   | 1575 | 21            |
| Nov 8, 2022 00:45:33 | 67.05kg | 21.4 | 11.7%    | 59.21kg              | 10.3%            | 5            | 63.8%      | 57.0%           | 56.25kg     | 2.96kg    | 20.1%   | 1648 | 18            |
| Nov 8, 2022 00:45:55 | 61.60kg | 19.7 | 9.0%     | 56.06kg              | 8.0%             | 3            | 65.7%      | 58.8%           | 53.22kg     | 2.84kg    | 20.7%   | 1596 | 20            |
| Nov 8, 2022 00:46:28 | 61.60kg | 19.7 | -        | -                    | -                | -            | -          | -               | -           | -         | -       | -    | -             |

I will make more measurements with different profiles later.

[btsnoop_hci.log](https://github.com/oliexdev/openScale/files/10036798/btsnoop_hci.log)

**Discover Bluetooth services and characteristic**

[openScale_2022-11-17_23-02.txt](https://github.com/oliexdev/openScale/files/10036800/openScale_2022-11-17_23-02.txt)

### Implementation Status

I have already implemented the code to read and parse the weight and will open a draft PR in a minute.
I have no idea where to go from here tho. I'm assuming I'll need to reverse some kind of library like on the QNScale to get the remaining values.

### PR DESCRIPTION
**Pull request by diogotcorreia**
Closes #900

#### Measurements

- [x] Weight
- [ ] Body fat
- [ ] Body water
- [ ] Muscle mass
- [ ] Protein
- [ ] Base Metabolic Rate (BMR)

#### Features

- [x] Connect to scale
- [ ] Disconnect gracefully from scale
- [x] Offline measurements
- [ ] Initial pairing (? not sure if this is needed, I wasn't the one setting up the scale)
- [ ] Low battery alert

Will add bullet points as I go

### CODE REVIEW

**Comment by oliexdev** [comment]
Thanks for your effort, looks so far good.

**Comment by diogotcorreia** [comment]
Thank you!
I did not have time to continue reversing the lib yet, but I'll continue when I do :)

**Comment by oliexdev** [comment]
I will merge the current status of your PR into the master branch for those people who have this scale can at least sync their weight. Thanks for that! If you have an updated PR please reopen it or create a new one.

**Comment by diogotcorreia** [comment]
@oliexdev Great! I don't think I will continue reversing this since (at least 1.5 years ago) the calculation of all other metrics was completely "fake" (see https://github.com/oliexdev/openScale/issues/900#issuecomment-1424466223).
Weight should be the only relevant metric from this scale :upside_down_face:

**Pull request merged**
