### PR TITLE
fix senssun saving issue

### PR DESCRIPTION
**Pull request by gmarco**
added time/Date function
fixed saving issue

model B support (but getBluetoothGattServices not working as in Version before, must be fixed later)

### CODE REVIEW

**Comment by gmarco** [comment]
initial connection take a while, with new version, but after first connect, connection is good

**Comment by oliexdev** [comment]
`onBluetoothDiscovery` will never be called because `discoverBluetoothServices()`is never called!?
What is the difference between model A and model B? Do they have different device names?

**Comment by gmarco** [comment]
yes the have different names (id's copied from the original source).
the function was (in different named functions) working in last releases.
UUID cmdMeasurementCharacteristic;
UUID writeCharacteristic;
are different, the code itself is the same.

ahhh i see there is a copy paste error
MODEL_B_MEASUREMENT_SERVICE = 0000ffb0
 MODEL_B_NOTIFICATION_CHARACTERISTIC = 0000ffb2
MODEL_B_WRITE_CHARACTERISTIC = 0000ffb2

can you change this on merge ?
i onlyl got model A and cannot test B

**Comment by oliexdev** [comment]
I added a new branch at https://github.com/oliexdev/openScale/tree/SenssunScale based on your gist link.

I don't own this scale, so please test [this version](https://github.com/oliexdev/openScale/releases/tag/travis-dev_SenssunScale-build) and attached the openScale log file here.

**Comment by gmarco** [comment]
i'll try this branch next days, but this code is complete different (posted from other user after inserting this scale here), and does again not save the weigth, if no fat measurement ws successfull.

**Comment by quthla** [comment]
> I added a new branch at https://github.com/oliexdev/openScale/tree/SenssunScale based on your gist link.
> 
> I don't own this scale, so please test [this version](https://github.com/oliexdev/openScale/releases/tag/travis-dev_SenssunScale-build) and attached the openScale log file here.

Tried this. It will not save dozens of measurements anymore

**Comment by oliexdev** [comment]
please add the openscale log file with and without a fat measurement with this scale.

**Comment by gmarco** [comment]
the code for that is in that pull request, i must take a look for those files now. but in short: the scale is not sending any further data. No failed messages, no end message, nothing. simple the AA with the weight and nothing more (readable in the code in the pr)

**Comment by oliexdev** [comment]
@gmarco please user proper markdown formatting to paste logfiles in GitHub, so the log format is not destroyed and please add the whole log file. Thanks.

**Comment by oliexdev** [comment]
I guess there are no problems anymore.

**Pull request closed without merging**
