### PR TITLE
fix for issue #548: support for 1byOne model CF398BLE

### PR DESCRIPTION
**Pull request by joergmlpts**
- fix for issue #548: support for 1byOne model CF398BLE while maintaining compatibility with old 20-byte measurements
- set clock and download and delete history of 1byOne scales

### CODE REVIEW

**Comment by oliexdev** [comment]
Unfortunately, I can't test this improvement because I don't own this scale but I assume you have tested it. Thanks.

**Comment by joergmlpts** [comment]
Testing worked best for me with v2.2.0. In 2.3.0 I also ran into the fatal that **firebovine** already described 3 weeks ago in a comment to issue 548:
```
Stack trace: 
java.lang.IllegalArgumentException: ID does not reference a View inside this Activity
	at android.app.Activity.requireViewById(Activity.java:2691)
	at androidx.core.app.ActivityCompat.requireViewById(ActivityCompat.java:363)
	at androidx.navigation.Navigation.findNavController(Navigation.java:58)
	at com.health.openscale.gui.preferences.BluetoothSettingsFragment$BluetoothDeviceView.onClick(BluetoothSettingsFragment.java:359)
	at android.view.View.performClick(View.java:6669)
	at android.view.View.performClickInternal(View.java:6638)
	at android.view.View.access$3100(View.java:789)
	at android.view.View$PerformClick.run(View.java:26145)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Might this exception be caused by your change to navigation back in June? This seems unrelated to this particular scale.

**Comment by oliexdev** [comment]
should be fixed in the v2.3.1, see issue #608

**Comment by joergmlpts** [comment]
Unfortunately, I still see it in v2.3.1:

Screenshot_20200820-122908

**Pull request merged**
