### PR TITLE
Activity state

### PR DESCRIPTION
**Pull request by erijo**
Make data entry activity and graph and table fragment remember the state so that when the user e.g. rotates the screen, the state isn't lost.

Also made switching year in graph view move from e.g. January 2018 to December 2017 instead of to January 2017.

### CODE REVIEW

**Comment by oliexdev** [comment]
Can you please change the "static private" to the correct order "private static".
Also please remove the NonNull annotations. Currently I don't want to use any code inspections inside the source code. Thanks.

**Comment by erijo** [comment]
Sure thing, I'll fix it.

**Comment by erijo** [comment]
@oliexdev: fixed now

**Comment by oliexdev** [comment]
thanks now it looks good. 👍

**Pull request merged**
