### PR TITLE
Readd NonNull annotation on ScaleUser gender and scaleUnit

### PR DESCRIPTION
**Pull request by erijo**
Removing the annotations requires adding a database migration as the scheme changes.

### CODE REVIEW

**Comment by oliexdev** [comment]
yes but it is in the development version of openScale, so we don't need any migration strategy. People who using the development version should be aware of bugs or experimental source code changes.

**Comment by erijo** [comment]
But this is a change between 1.7 and the dev version. If you run the DatabaseMigration test you'll see that it fails.

**Comment by erijo** [comment]
I added the NonNull annotation when I changed gender and scaleUnit from ints to enums as when they were ints, room automatically made them non-null, and to avoid changing the database scheme I added the NonNull annotation which makes room generate the scheme as before the change.

**Comment by oliexdev** [comment]
Ok I see, then we have to change the migration method or we use the nonnull method again but I think its more confusing for people who will look into the source code, why only these variables have a nonnull annotation.

**Comment by erijo** [comment]
If you merge this @oliexdev, I can work on removing the annotations and adding the migration.

**Comment by oliexdev** [comment]
ok thx

**Pull request merged**
