### PR TITLE
Add measurement widget

### PR DESCRIPTION
**Pull request by erijo**
The widget can be added to the home screen and can be configured to
show any of the measurements that are enabled. It can also be resized
from 1x1 to <max width>x1, adapting to the size change and showing a
reasonable amount of information at each size. The default size is
4x1.

### CODE REVIEW

**Comment by oliexdev** [comment]
awesome @erijo I just added an colour evaluation indicator and for one-cell-widget an icon on top.

**Comment by erijo** [comment]
I like the evaluation indicator. Nice!

But the icon in 1x1 mode pushes the unit halfway outside the widget. Try e.g BMR or weight when it's 100+.

**Comment by erijo** [comment]
The delta value is still not visible.

**Comment by oliexdev** [comment]
not on my smartphone :/

**Comment by erijo** [comment]
You may need to test with a less high end emulator then :)

**Comment by oliexdev** [comment]
now it should work also with small density devices at least I have tested it with a simulated Nexus 5 device.

**Comment by erijo** [comment]
I did a few more changes. Now I can see the unit as well on my device :)

**Comment by oliexdev** [comment]
but now it looks a bit wired on devices with high resolutions. ;)
Anyway, we have something working.

**Comment by erijo** [comment]
Which resolution/device does it look weird on? Also could you please elaborate on what you mean with weird? I would like to look into it a bit.

**Comment by erijo** [comment]
I tested in an emulator using a Pixel 2 device and it seems like the widget is higher that it is wide. On a low res device width and height for a 1x1 widget seems more equal.

I did some small changes like changing text alignment to center instead of right and allowing value to be 2 lines (otherwise the unit isn't shown for 100+ weight). I think it looks acceptable on all devices I've tested on now.

What do you think?

**Pull request merged**
