### PR TITLE
Fixed auto backup;

### PR DESCRIPTION
**Pull request by FFDA**
Made auto backup compatible with SAF.

- Dev-build had some fixes for Andriod10+ devices that allowed to check "Auto backup" checkbox in settings. However, it still used [getExternalFilesDir()](https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)) that returns directory that is hard to reach and is deleted when app is removed from the device. Moreover (while I didn't check it on dev-build), there is [a comment](https://github.com/oliexdev/openScale/issues/816#issuecomment-1380063080) that this issues still persisted even with the fix.
- This fix asks user to select a directory where to store the backup database(s) and lets it change later;
- Added "Test auto backup" button.

While all the issues are closes this pull request fixes: https://github.com/oliexdev/openScale/issues/816 https://github.com/oliexdev/openScale/issues/867 https://github.com/oliexdev/openScale/issues/859 https://github.com/oliexdev/openScale/issues/684

Tested on Android12 physical device and Android6, Android9 and Android12 virtual devices.

Screenshot of how backup preferences looks now:
https://user-images.githubusercontent.com/8406967/218267366-39b11c82-7eca-490e-a35e-9e30b767beff.png

### CODE REVIEW

**Comment by oliexdev** [comment]
Thanks @FFDA  for your PR. Could you remove the Test auto backup button or move it to the settings->About->Development because I don't want to have any test buttons in the main menus.

**Comment by FFDA** [comment]
> Thanks @FFDA  for your PR. Could you remove the Test auto backup button or move it to the settings->About->Development because I don't want to have any test buttons in the main menus. 

Which option do you prefer?

**Comment by oliexdev** [comment]
then I would prefer to remove it.

**Comment by FFDA** [comment]
I removed the backup test button from the settings.

**Comment by oliexdev** [comment]
Thanks :+1:

**Comment by FFDA** [comment]
Yeah, my bad. I actually tried about it and added this code:
```
DocumentFile exportDir = DocumentFile.fromTreeUri(context, Uri.parse(exportDirString));
// Check if it is possible to read and write to auto export dir
// If it is not possible auto backup function will be disabled
if (!exportDir.canRead() || !exportDir.canWrite()) {
    SharedPreferences.Editor editor = prefs.edit();
    editor.putBoolean("autoBackup", false);
    editor.apply();
    return;
}
```
It seems it didn't work :/ And I only tested on new installs.

**Pull request merged**
