### PR TITLE
Spelling: Time to weigh → Time to weigh in

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by erijo** [comment]
I'm not so sure about this. Could you please elaborate on why you think it should be like this?

@bontibon: as you just changed this string, do you have an opinion on this?

What about changing it to "Time to weigh yourself"?

**Comment by bontibon** [comment]
"Time to weigh in" and "Time to weight yourself" are both an improvement, though I think the latter reads better.

**Comment by comradekingu** [comment]
My sentiment is that "in" is shorter than "yourself", and it isn't always the case that the person reading it is the person weighed. I think the figure of speech attentive to the action, rather than the person, makes it seem more integrated with the language. Not in the least because English is very much focused around actions.

**Comment by erijo** [comment]
Ok, you've convinced me. Thank you both!

**Comment by oliexdev** [comment]
btw this text is editable by the user...

**Pull request merged**
