### PR TITLE
Add support for Silvercrest SBF75 scale

### PR DESCRIPTION
**Pull request by matushorvath**
Hello

I added support for SilverCrest SBF75 scale, which looks like a rebranded Sanitas SBF70 with a different device name. As far as I can tell, the scale works fine with these changes.

Thank you

Matus

### CODE REVIEW

**Comment by oliexdev** [comment]
thanks @matushorvath please report if something doesn't work.

**Comment by atmaniak** [comment]
Using the current dev build, the app is crashing when the scale is mesuring others data (not weight).
Weight is not saved.

**Comment by matushorvath** [comment]
@atmaniak I will install a current build and try it out. Are you using a SBF75 or SBF70 scale?

**Comment by atmaniak** [comment]
The sticker says : 
Type: SBF 75

**Pull request merged**
