### PR TITLE
Some more misc changes

### PR DESCRIPTION
**Pull request by erijo**
Fixes a few minor issues that I've come across. Please see individual commits for more info.

### CODE REVIEW

**Comment by oliexdev** [comment]
Thanks could you change the behaviour of the left/right buttons that they are not disappear but for instead that they are disabled (e.g. gray).

**Comment by erijo** [comment]
@oliexdev: better now?

**Comment by oliexdev** [comment]
Thanks, I implemented a combined approach. :wink:  So I will disable all navigations buttons if we don't need them. Otherwise the navigations buttons are disabled at the end like you implemented it.
Additionally, I fixed a conversion bug in the evaluation sheet.

**Comment by erijo** [comment]
Good combination!

Good catch with the evaluation sheet conversion bug!

**Pull request merged**
