### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by erijo**
A couple of minor fixes/improvements. See individual commits for more info.

### CODE REVIEW

**Comment by oliexdev** [comment]
thanks for your PR.

commit d8b6458 , 62c54f9 and b00fb1e were accepted.

For 9b7121f I don't really understand the commit you reset the diff value but we update it again anyway?

For a8bd2cc I only changed that we use the isVisible method but I didn't refactor the method itself because its more clear to understand the method.

**Comment by erijo** [comment]
If diffValue is set when updateValue is called, it will trigger a call to updateDiffValue. But this is unnecessary as we know that updateDiffValue will be called directly after updateValue anyway.

The reason for this attempt to optimize things is that I noticed that it took some time to switch between entries in the dataentry view and I wanted to speed that up.

**Comment by oliexdev** [comment]
I guess its so slow because every time you switch between the data a sql access is executed to get a tuple of data (previous, selected and next one) because I need the correct id which is not continues.

**Comment by erijo** [comment]
I thought so as well initially @oliexdev. But after doing some very rudimentary measurements it looked like reading from the database was fairly quick and that most of the time was spent updating the measurement views. But this was in the emulator and my computer is too slow so it's almost painful to use...

Could you try with and without 9b7121f and see if you can see any difference?

**Pull request closed without merging**
